config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "exchange_reports#index"
    end

    unauthenticated do
      root "devise/sessions#new"
    end
  end
  resources :exchange_reports
  get "/info", to: "exchange_reports#info"
end

app/models/exchange_report.rb
# frozen_string_literal: true

class ExchangeReport < ApplicationRecord
  CURRENCIES = %w[AUD BGN BRL CAD CHF CNY CZK DKK
                  EUR GBP HKD HRK HUF IDR ILS INR JPY
                  KRW MXN MYR NOK NZD PHP PLN RON RUB
                  SEK SGD THB TRY USD ZAR].freeze

  validates_inclusion_of :amount, in: 1..1000000, message: "must be in 1 - 1000000"
  validates_inclusion_of :max_wait_time_in_weeks, in: 1..250, message: "must be in 1 - 250"

  validates_inclusion_of :base_currency, :target_currency, in: CURRENCIES, message: "not supported"
  validate :base_and_target_currency_cannot_be_same

  before_save :calculate_corresponding_future_dates
  belongs_to :user
  has_and_belongs_to_many :exchange_rates, -> { order(date: :desc) }

  def base_and_target_currency_cannot_be_same
    errors.add(:target_currency, "can't be same as base currency") if base_currency == target_currency && base_currency.present?
  end

  def collect_data
    exchange_rates.destroy_all if exchange_rates.present?

    creation_date_monday = created_at.beginning_of_week
    (max_wait_time_in_weeks + 1).times do |i|
      week_to_find = (creation_date_monday - i.weeks).strftime("%Y-%m-%d")
      exchange_rate = ExchangeRate.find_by(date: week_to_find, base_currency: base_currency, target_currency: target_currency)
      if exchange_rate.blank? # need to make api call to get data
        begin
          result = HTTParty.get "https://api.fixer.io/#{week_to_find}?base=#{base_currency}&symbols=#{target_currency}", timeout: 2
        rescue Net::OpenTimeout
          result = HTTParty.get "https://api.fixer.io/#{week_to_find}?base=#{base_currency}&symbols=#{target_currency}", timeout: 2
        end
        if result.parsed_response.include? "Too Many Requests"
          sleep 5
          result = HTTParty.get "https://api.fixer.io/#{week_to_find}?base=#{base_currency}&symbols=#{target_currency}", timeout: 2
        end
        exchange_rate = ExchangeRate.create(
          base_currency: result["base"],
          target_currency: result["rates"].first.first,
          date: week_to_find,
          rate: result["rates"].first.last
        )
      end
      exchange_rate.calculate_prediction
      exchange_rates << exchange_rate
    end
    update_columns(best_weeks_ids: calculate_best_weeks_ids)
  end

  def conversion_currencies
    "#{base_currency} -> #{target_currency}"
  end

  def target_currency_amount(rate)
    return (amount * rate.rate).round(2) if rate == exchange_rates.first
    (amount * rate.prediction).round(2)
  end

  # amount to receive if exchange money without waiting
  def amount_no_waiting
    return 0 if exchange_rates&.first&.rate.blank?
    (amount * exchange_rates&.first&.rate).round(2)
  end

  def color_class(rate)
    return "text-success" if target_currency_amount(rate) > amount_no_waiting
    return "text-danger" if target_currency_amount(rate) < amount_no_waiting
    ""
  end

  def profit_or_loss(rate)
    target_currency_amount(rate) - amount_no_waiting
  end

  def data_for_chart
    chart_data = []
    exchange_rates.each_with_index do |rate, index|
      step = []
      step << future_dates[index].strftime("%Y - %W")
      step << target_currency_amount(rate)
      chart_data << step
    end
    chart_data
  end

  def calculate_corresponding_future_dates
    self.future_dates = []
    if new_record?
      generation_date = Date.today.beginning_of_week
    else
      generation_date = created_at.beginning_of_week
    end

    future_dates << generation_date
    1.upto(max_wait_time_in_weeks) do |i|
      future_dates << generation_date + i.weeks
    end
  end

  def calculate_best_weeks_ids
    exchange_rates.sort_by { |rate| -rate.prediction }.first(3).map(&:id)
  end

  def top_three?(exchange_rate_id)
    return true if best_weeks_ids.include?(exchange_rate_id)
    false
  end

  def rank_number(exchange_rate_id)
    case exchange_rate_id
    when best_weeks_ids[0]
      1
    when best_weeks_ids[1]
      2
    when best_weeks_ids[2]
      3
    else
      ""
    end
  end
end

# == Schema Information
#
# Table name: exchange_reports
#
#  id                     :integer          not null, primary key
#  base_currency          :string(3)        not null
#  target_currency        :string(3)        not null
#  amount                 :decimal(, )      not null
#  max_wait_time_in_weeks :integer          not null
#  user_id                :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  future_dates           :date             default([]), is an Array
#  best_weeks_ids         :integer          default([]), is an Array
#

app/controllers/exchange_reports_controller.rb
# frozen_string_literal: true

class ExchangeReportsController < ApplicationController
  before_action :authenticate_user!, except: [:info]
  load_and_authorize_resource except: [:info, :index, :show]

  def index
    @exchange_reports = ExchangeReport.all
  end

  def new; end

  def create
    if @exchange_report.save
      @exchange_report.collect_data
      flash[:notice] = "Successfully created report"
      redirect_to @exchange_report
    else
      flash.now[:alert] = "Failed to create report"
      render :new
    end
  end

  def show
    @exchange_report = ExchangeReport.find(params[:id])
  end

  def edit; end

  def update
    if @exchange_report.update_attributes(exchange_report_params)
      @exchange_report.collect_data
      flash[:notice] = "Successfully updated report"
      redirect_to @exchange_report
    else
      flash.now[:alert] = "Failed to update report"
      render :edit
    end
  end

  def destroy
    if @exchange_report.destroy
      flash[:notice] = "Successfully deleted report"
      redirect_to root_path
    else
      flash.now[:alert] = "Failed to delete report"
      render :index
    end
  end

  def info; end

  private

    def exchange_report_params
      params.require(:exchange_report).permit(:amount, :max_wait_time_in_weeks, :base_currency, :target_currency)
    end
end

app/views/exchange_reports/_form.html.erb
<%= link_to root_path, class: 'btn btn-custom' do %>
  <%= fa_icon "chevron-circle-left", text: "Back" %>
<% end %>
<br>
<br>
<h4>Exchange Report</h4>
<br>
<%= form_for @exchange_report do |f| %>
  <% if f.object.errors.any? %>
    <ul class="alert alert-danger">
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.label "Amount of money" %>
  	<%= f.number_field :amount, class: "form-control", min: 1, max: 1000000, required: true %>
    <br>
    <div>
      <%= f.label "Max waiting time in weeks: " %>
      <span id="rangeFieldVal"><%= (f.object.max_wait_time_in_weeks || 1) %></span>      
    </div>
    <%= f.range_field :max_wait_time_in_weeks, in: 1..250, value: (f.object.max_wait_time_in_weeks || 1),
      class: "form-control" %>
    <br>
    <%= f.label "Base currency" %>
    <%= f.select :base_currency, options_for_select(ExchangeReport::CURRENCIES, f.object.base_currency), {}, class: "custom-select", required: true %>
    <br>
    <br>
    <%= f.label "Target currency" %>
    <%= f.select :target_currency, options_for_select(ExchangeReport::CURRENCIES, f.object.target_currency), {}, class: "custom-select", required: true %>
    <br>
    <br>
    <%= f.submit "Submit", class: "btn btn-custom", disabled: true %>
  </div>
  <br>
  <strong>NB! IMPORTANT: The fixer API endpoint has been deprecated. It's not possible to create new reports at the momemt. </strong>
<% end %>

app/views/exchange_reports/edit.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <strong>It is possible to edit Your existing Exchange Report here.</strong>
    </div>
  </div>
</div>

app/views/exchange_reports/index.html.erb
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <% if @exchange_reports.present? %>
        <h2>Your Currency Exchange Reports</h2>
        <br>
        <table class="table">
          <tr>
            <th>Number</th>
            <th>Currency Conversion</th>
            <th>Generation Date</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
          <% @exchange_reports.each_with_index do |exchange_report, index| %>
            <tr>
              <td><%= index + 1%></td>
              <td><%= exchange_report.conversion_currencies %></td>
              <td><%= exchange_report.created_at.strftime('%d.%m.%Y %H:%M') %></td>
              <th>
                <%= link_to exchange_report_path(exchange_report), class: 'btn btn-custom btn-sm' do %>
                  <%= fa_icon "eye", text: "View" %>
                <% end %>
              </th>
              <th>
                <%= link_to edit_exchange_report_path(exchange_report), class: 'btn btn-custom btn-sm' do %>
                  <%= fa_icon "edit", text: "Edit" %>
                <% end %>
              </th>
              <th>
                <%= link_to exchange_report_path(exchange_report), class: 'btn btn-custom btn-sm' , data: {confirm: 'Are you sure?'}, method: :delete do %>
                  <%= fa_icon "trash", text: "Delete" %>
                <% end %>
              </th>
            </tr>
          <% end %>
        </table>
      <% else %>
        <h5>You don't have any exchange reports yet. Click 'New report'
         in navigation menu to create one.</h5>
      <% end %>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <br>
      <strong>This is a web app that helps You to decide when to exchange your currency. Supported currencies are: <%= ExchangeReport::CURRENCIES.join(', ') %>.</strong>
    </div>
  </div>
</div>

app/views/exchange_reports/info.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-5">
      <strong>THE FIXER API ENDPOINT HAS BEEN DEPRECATED. AT THE MOMEMT IT IS ONLY POSSIBLE TO VIEW PREVIOUSLY CREATED REPORTS.</strong>
      <br>
      <br>
      <p>This is a web app that helps You to decide when to exchange money
      from one currency to another.</p>
      <p>Written using Ruby on Rails framework.</p>
      <p>Rails version: <strong>5.1.5</strong></p>
      <p>Ruby version: <strong>2.4.1</strong></p>
      <p>App makes API requests to fetch currency exchange rates. Identical request is never made twice.</p>
      <p>The more this app is used, the more currency exchange rates data is saved to database.</p>
      <p>This means that speed and reliability grow with use.</p>
      <p>Report generation time can be about one minute if making report with 250 weeks and all of the rates need to be fetched through API (due to API limitations).
      </p>
      <strong>NB! This app is not intended for real-world use; The prediction algorithm simply uses randomness.</strong>
    </div>
  </div>
  <br>
  <%= link_to root_path, class: 'btn btn-custom' do %>
    <%= fa_icon "chevron-circle-left", text: "Back" %>
  <% end %>
</div>
<br>

app/views/exchange_reports/new.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <br>
      <strong>API requests will be made only if necessary data is missing from the database.</strong>
    </div>
  </div>
</div>

app/views/exchange_reports/show.html.erb
<div class="container">
  <%= link_to root_path, class: 'btn btn-custom' do %>
    <%= fa_icon "chevron-circle-left", text: "Back" %>
  <% end %>
  <br>
  <br>
  <div class="row">
    <div class="col-12">
      <h2>Currency Exchange Report</h2>
      <hr>
      <strong>
        <p>
          Exchanging from: <%= @exchange_report.base_currency %>
        </p>
        <p>
          Exchanging to: <%= @exchange_report.target_currency %>
        </p>
        <p>
          <%= "Amount of #{@exchange_report.base_currency} to exchange: 
          #{number_with_precision(@exchange_report.amount, precision: 2)}" %>
        </p>
        <p>
          Report creation year and week: <%= @exchange_report.created_at.strftime('%Y - %W') %>
        </p>
        <p>
          <%= "Amount of #{@exchange_report.target_currency} to receive
          if exchanging without waiting: 
            #{number_with_precision(@exchange_report.amount_no_waiting, precision: 2)}" %>
        </p>
      </strong>
      <hr>
      <br>
      <h3>Chart</h3>
      <br>
      <%= line_chart @exchange_report.data_for_chart, min: 0.6 * @exchange_report.amount_no_waiting,
        max: 1.4 * @exchange_report.amount_no_waiting, curve: false, xtitle: "Year and week",
        ytitle: "Amount to receive" %>
      <br>
      <br>
      <h3>Detailed table</h3>
      <br>
      <table class="table">
        <tr>
          <th>Rank</th>
          <th>Year and week</th>
          <th>Rate from past</th>
          <th>Predicted rate</th>
          <th><%= "Amount of #{@exchange_report.target_currency}" %> </th>
          <th>Profit/Loss</th>
        </tr>
        <% @exchange_report.exchange_rates.each_with_index do |exchange_rate, index| %>
          <tr class="<%= 'top-three' if @exchange_report.top_three?(exchange_rate.id) %>">
            <td><strong><%= @exchange_report.rank_number(exchange_rate.id) %></strong></td>
            <td><%= @exchange_report.future_dates[index].strftime('%Y - %W') %></td>
            <td><%= exchange_rate.rate %></td>
            <td><%= exchange_rate.prediction %></td>
            <td class="<%= @exchange_report.color_class(exchange_rate) %>">
              <%= index.zero? ? 
                number_with_precision(@exchange_report.amount_no_waiting, precision: 2) :
                @exchange_report.target_currency_amount(exchange_rate) %></td>
            <td class="<%= @exchange_report.color_class(exchange_rate) %>">
              <%= number_with_precision(@exchange_report.profit_or_loss(exchange_rate), 
                precision: 2) %></td>
          </tr>
        <% end %>
      </table>
      <br>
      <%= link_to root_path, class: 'btn btn-custom' do %>
        <%= fa_icon "chevron-circle-left", text: "Back" %>
      <% end %>
    </div>
  </div>
  <br>
</div>