config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "exchange_reports#index"
    end

    unauthenticated do
      root "devise/sessions#new"
    end
  end
  resources :exchange_reports
  get "/info", to: "exchange_reports#info"
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
	</button>

  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= fa_icon "gg", text: "Exchange Helper" %>
  <% end %>
  
  <div class="collapse navbar-collapse" id="nav-content">
	<ul class="navbar-nav">
    <% if current_user.present? %>
    	<li class="nav-item <%= 'active' if action_name == 'new' %>">
        <%= link_to new_exchange_report_path, class: 'nav-link' do %>
          <%= fa_icon "plus-circle", text: "New report" %>
        <% end %>
    	</li>
    <% end %>
  	<li class="nav-item <%= 'active' if action_name == 'info' %>">
      <%= link_to info_path, class: 'nav-link' do %>
        <%= fa_icon "info-circle", text: "Information" %>
      <% end %>
  	</li>
	</ul>

  <% if current_user.present? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div class="navbar-text">
          <%= fa_icon "user", text: current_user.username %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
          <%= fa_icon "sign-out", text: "Log Out" %>
        <% end %>
      </li>
    </ul>
  <% end %>
</nav>
<br>